name: file_md5
resolution: workspace
description: A Flutter package with streamed MD5 calculation.
version: 0.2.1+1
homepage: https://github.com/jiejie-dev/flutter_file_md5

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.2
  async: ^2.8.2
  convert: ^3.0.1

dev_dependencies:
  test: ^1.24.0
